package aplicacion.datos.hibernate.mapeos;
// Generated 21/06/2018 23:30:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Autores generated by hbm2java
 */
public class Autores  implements java.io.Serializable {


     private Integer autCodigo;
     private String autApellidos;
     private String autNombres;
     private Set pubAuts = new HashSet(0);

    public Autores() {
    }

	
    public Autores(String autApellidos, String autNombres) {
        this.autApellidos = autApellidos;
        this.autNombres = autNombres;
    }
    public Autores(String autApellidos, String autNombres, Set pubAuts) {
       this.autApellidos = autApellidos;
       this.autNombres = autNombres;
       this.pubAuts = pubAuts;
    }
   
    public Integer getAutCodigo() {
        return this.autCodigo;
    }
    
    public void setAutCodigo(Integer autCodigo) {
        this.autCodigo = autCodigo;
    }
    public String getAutApellidos() {
        return this.autApellidos;
    }
    
    public void setAutApellidos(String autApellidos) {
        this.autApellidos = autApellidos;
    }
    public String getAutNombres() {
        return this.autNombres;
    }
    
    public void setAutNombres(String autNombres) {
        this.autNombres = autNombres;
    }
    public Set getPubAuts() {
        return this.pubAuts;
    }
    
    public void setPubAuts(Set pubAuts) {
        this.pubAuts = pubAuts;
    }




}


