package aplicacion.datos.hibernate.mapeos;
// Generated 21/06/2018 23:30:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Editoriales generated by hbm2java
 */
public class Editoriales  implements java.io.Serializable {


     private Integer ediCodigo;
     private String editNombre;
     private boolean editEstado;
     private Set publicacioneses = new HashSet(0);

    public Editoriales() {
    }

    public Editoriales(Integer ediCodigo, String editNombre, boolean editEstado) {
        this.ediCodigo = ediCodigo;
        this.editNombre = editNombre;
        this.editEstado = editEstado;
    }
    

	
    public Editoriales(String editNombre, boolean editEstado) {
        this.editNombre = editNombre;
        this.editEstado = editEstado;
    }
    public Editoriales(String editNombre, boolean editEstado, Set publicacioneses) {
       this.editNombre = editNombre;
       this.editEstado = editEstado;
       this.publicacioneses = publicacioneses;
    }
   
    public Integer getEdiCodigo() {
        return this.ediCodigo;
    }
    
    public void setEdiCodigo(Integer ediCodigo) {
        this.ediCodigo = ediCodigo;
    }
    public String getEditNombre() {
        return this.editNombre;
    }
    
    public void setEditNombre(String editNombre) {
        this.editNombre = editNombre;
    }
    public boolean isEditEstado() {
        return this.editEstado;
    }
    
    public void setEditEstado(boolean editEstado) {
        this.editEstado = editEstado;
    }
    public Set getPublicacioneses() {
        return this.publicacioneses;
    }
    
    public void setPublicacioneses(Set publicacioneses) {
        this.publicacioneses = publicacioneses;
    }




}


