package aplicacion.datos.hibernate.mapeos;
// Generated 21/06/2018 23:30:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Perfiles generated by hbm2java
 */
public class Perfiles  implements java.io.Serializable {

    private boolean perEstado;
     private Integer perCodigo;
     private Usuarios usuarios;
     private String perApellidos;
     private String perNombres;
     private String perDni;
     private Date perFechaNac;
     private String perEmail;
     private String perDireccion;
     private String perTelefono;

    public Perfiles() {
    }

    public Perfiles(boolean perEstado, Usuarios usuarios, String perApellidos, String perNombres, String perDni, Date perFechaNac, String perEmail, String perDireccion, String perTelefono) {
        this.perEstado = perEstado;
        
        this.usuarios = usuarios;
        this.perApellidos = perApellidos;
        this.perNombres = perNombres;
        this.perDni = perDni;
        this.perFechaNac = perFechaNac;
        this.perEmail = perEmail;
        this.perDireccion = perDireccion;
        this.perTelefono = perTelefono;
    }
    

	
    public Perfiles(Usuarios usuarios, String perApellidos, String perNombres, String perDni, Date perFechaNac, String perEmail, String perDireccion, String perTelefono) {
        this.usuarios = usuarios;
        this.perApellidos = perApellidos;
        this.perNombres = perNombres;
        this.perDni = perDni;
        this.perFechaNac = perFechaNac;
        this.perEmail = perEmail;
        this.perDireccion = perDireccion;
        this.perTelefono = perTelefono;
    }
    public Perfiles(Usuarios usuarios, String perApellidos, String perNombres, String perDni, Date perFechaNac, String perEmail, String perDireccion, String perTelefono, Set reservases, Set prestamoses) {
       this.usuarios = usuarios;
       this.perApellidos = perApellidos;
       this.perNombres = perNombres;
       this.perDni = perDni;
       this.perFechaNac = perFechaNac;
       this.perEmail = perEmail;
       this.perDireccion = perDireccion;
       this.perTelefono = perTelefono;
    }
   
    public Integer getPerCodigo() {
        return this.perCodigo;
    }
    
    public void setPerCodigo(Integer perCodigo) {
        this.perCodigo = perCodigo;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getPerApellidos() {
        return this.perApellidos;
    }
    
    public void setPerApellidos(String perApellidos) {
        this.perApellidos = perApellidos;
    }
    public String getPerNombres() {
        return this.perNombres;
    }
    
    public void setPerNombres(String perNombres) {
        this.perNombres = perNombres;
    }
    public String getPerDni() {
        return this.perDni;
    }
    
    public void setPerDni(String perDni) {
        this.perDni = perDni;
    }
    public Date getPerFechaNac() {
        return this.perFechaNac;
    }
    
    public void setPerFechaNac(Date perFechaNac) {
        this.perFechaNac = perFechaNac;
    }
    public String getPerEmail() {
        return this.perEmail;
    }
    
    public void setPerEmail(String perEmail) {
        this.perEmail = perEmail;
    }
    public String getPerDireccion() {
        return this.perDireccion;
    }
    
    public void setPerDireccion(String perDireccion) {
        this.perDireccion = perDireccion;
    }
    public String getPerTelefono() {
        return this.perTelefono;
    }
    
    public void setPerTelefono(String perTelefono) {
        this.perTelefono = perTelefono;
    }

    /**
     * @return the perEstado
     */
    public boolean isPerEstado() {
        return perEstado;
    }

    /**
     * @param perEstado the perEstado to set
     */
    public void setPerEstado(boolean perEstado) {
        this.perEstado = perEstado;
    }




}


