package aplicacion.datos.hibernate.mapeos;
// Generated 21/06/2018 23:30:40 by Hibernate Tools 4.3.1



/**
 * PubAut generated by hbm2java
 */
public class PubAut  implements java.io.Serializable {


     private Integer paCodigo;
     private Autores autores;
     private Publicaciones publicaciones;
     private boolean paEstado;

    public PubAut() {
    }

    public PubAut(Autores autores, Publicaciones publicaciones, boolean paEstado) {
       this.autores = autores;
       this.publicaciones = publicaciones;
       this.paEstado = paEstado;
    }
   
    public Integer getPaCodigo() {
        return this.paCodigo;
    }
    
    public void setPaCodigo(Integer paCodigo) {
        this.paCodigo = paCodigo;
    }
    public Autores getAutores() {
        return this.autores;
    }
    
    public void setAutores(Autores autores) {
        this.autores = autores;
    }
    public Publicaciones getPublicaciones() {
        return this.publicaciones;
    }
    
    public void setPublicaciones(Publicaciones publicaciones) {
        this.publicaciones = publicaciones;
    }
    public boolean isPaEstado() {
        return this.paEstado;
    }
    
    public void setPaEstado(boolean paEstado) {
        this.paEstado = paEstado;
    }




}


