package aplicacion.datos.hibernate.mapeos;
// Generated 21/06/2018 23:30:40 by Hibernate Tools 4.3.1



/**
 * PubCla generated by hbm2java
 */
public class PubCla  implements java.io.Serializable {


     private Integer pcCodigo;
     private Clasificaciones clasificaciones;
     private Publicaciones publicaciones;
     private boolean pcEstado;

    public PubCla() {
    }

    public PubCla(Integer pcCodigo, Clasificaciones clasificaciones, Publicaciones publicaciones, boolean pcEstado) {
        this.pcCodigo = pcCodigo;
        this.clasificaciones = clasificaciones;
        this.publicaciones = publicaciones;
        this.pcEstado = pcEstado;
    }

    public PubCla(Clasificaciones clasificaciones, Publicaciones publicaciones, boolean pcEstado) {
       this.clasificaciones = clasificaciones;
       this.publicaciones = publicaciones;
       this.pcEstado = pcEstado;
    }
   
    public Integer getPcCodigo() {
        return this.pcCodigo;
    }
    
    public void setPcCodigo(Integer pcCodigo) {
        this.pcCodigo = pcCodigo;
    }
    public Clasificaciones getClasificaciones() {
        return this.clasificaciones;
    }
    
    public void setClasificaciones(Clasificaciones clasificaciones) {
        this.clasificaciones = clasificaciones;
    }
    public Publicaciones getPublicaciones() {
        return this.publicaciones;
    }
    
    public void setPublicaciones(Publicaciones publicaciones) {
        this.publicaciones = publicaciones;
    }
    public boolean isPcEstado() {
        return this.pcEstado;
    }
    
    public void setPcEstado(boolean pcEstado) {
        this.pcEstado = pcEstado;
    }




}


