package aplicacion.datos.hibernate.mapeos;
// Generated 21/06/2018 23:30:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Publicaciones generated by hbm2java
 */
public class Publicaciones  implements java.io.Serializable {


     private String pubCodigo;
     private Editoriales editoriales;
     private String pubNombre;
     private String pubResumen;
     private boolean pubEstado;
     private String pubTipo;
     private int pubStock;
     private Set detallesReservases = new HashSet(0);
     private Set pubClas = new HashSet(0);
     private Set detallesPrestamoses = new HashSet(0);
     private Set pubAuts = new HashSet(0);

    public Publicaciones() {
    }

    public Publicaciones(String pubCodigo, Editoriales editoriales, String pubNombre, String pubResumen, boolean pubEstado, String pubTipo, int pubStock) {
        this.pubCodigo = pubCodigo;
        this.editoriales = editoriales;
        this.pubNombre = pubNombre;
        this.pubResumen = pubResumen;
        this.pubEstado = pubEstado;
        this.pubTipo = pubTipo;
        this.pubStock = pubStock;
    }

	
    public Publicaciones(String pubCodigo, Editoriales editoriales, String pubNombre, boolean pubEstado, String pubTipo, int pubStock) {
        this.pubCodigo = pubCodigo;
        this.editoriales = editoriales;
        this.pubNombre = pubNombre;
        this.pubEstado = pubEstado;
        this.pubTipo = pubTipo;
        this.pubStock = pubStock;
    }
    public Publicaciones(String pubCodigo, Editoriales editoriales, String pubNombre, String pubResumen, boolean pubEstado, String pubTipo, int pubStock, Set detallesReservases, Set pubClas, Set detallesPrestamoses, Set pubAuts) {
       this.pubCodigo = pubCodigo;
       this.editoriales = editoriales;
       this.pubNombre = pubNombre;
       this.pubResumen = pubResumen;
       this.pubEstado = pubEstado;
       this.pubTipo = pubTipo;
       this.pubStock = pubStock;
       this.detallesReservases = detallesReservases;
       this.pubClas = pubClas;
       this.detallesPrestamoses = detallesPrestamoses;
       this.pubAuts = pubAuts;
    }
   
    public String getPubCodigo() {
        return this.pubCodigo;
    }
    
    public void setPubCodigo(String pubCodigo) {
        this.pubCodigo = pubCodigo;
    }
    public Editoriales getEditoriales() {
        return this.editoriales;
    }
    
    public void setEditoriales(Editoriales editoriales) {
        this.editoriales = editoriales;
    }
    public String getPubNombre() {
        return this.pubNombre;
    }
    
    public void setPubNombre(String pubNombre) {
        this.pubNombre = pubNombre;
    }
    public String getPubResumen() {
        return this.pubResumen;
    }
    
    public void setPubResumen(String pubResumen) {
        this.pubResumen = pubResumen;
    }
    public boolean isPubEstado() {
        return this.pubEstado;
    }
    
    public void setPubEstado(boolean pubEstado) {
        this.pubEstado = pubEstado;
    }
    public String getPubTipo() {
        return this.pubTipo;
    }
    
    public void setPubTipo(String pubTipo) {
        this.pubTipo = pubTipo;
    }
    public int getPubStock() {
        return this.pubStock;
    }
    
    public void setPubStock(int pubStock) {
        this.pubStock = pubStock;
    }
    public Set getDetallesReservases() {
        return this.detallesReservases;
    }
    
    public void setDetallesReservases(Set detallesReservases) {
        this.detallesReservases = detallesReservases;
    }
    public Set getPubClas() {
        return this.pubClas;
    }
    
    public void setPubClas(Set pubClas) {
        this.pubClas = pubClas;
    }
    public Set getDetallesPrestamoses() {
        return this.detallesPrestamoses;
    }
    
    public void setDetallesPrestamoses(Set detallesPrestamoses) {
        this.detallesPrestamoses = detallesPrestamoses;
    }
    public Set getPubAuts() {
        return this.pubAuts;
    }
    
    public void setPubAuts(Set pubAuts) {
        this.pubAuts = pubAuts;
    }

    @Override
    public int hashCode() {
        return (pubCodigo != null)? (this.getClass().hashCode() + pubCodigo.hashCode()): super.hashCode();        
    }

    @Override
    public boolean equals(Object obj) {
            return (obj instanceof Publicaciones) && (pubCodigo != null)? pubCodigo.equals(((Publicaciones) obj).pubCodigo) :(obj == this);
             
    }

    @Override
    public String toString() {
        return String.format ("Publicaciones: [%s, %s]", pubCodigo, pubNombre);
    }    


}


